spring:
  profiles:
    active: dev
  application:
    name: user-center
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/user_center?serverTimezone=GMT%2B8
    username: root
    password: pwb2001
  #  session 失效时间
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  session:
    timeout: 86400
    store-type: redis
  redis:
    host: 172.20.10.9
    port: 6379
    password: 123456
    timeout: 1800000
    database: 0
    lettuce:
      pool:
        max-active: 20
        max-wait: 1
server:
  port: 8080
  servlet:
    context-path: /api
  address: 0.0.0.0
mybatis-plus:
  mapper-locations: classpath:com/user/usercenter/mapper/xml/*.xml
#    日志
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #开启sql日志
  global-config:
    db-config:
      logic-delete-field: flag # 全局逻辑删除的实体字段名(since 3.3.0,配置后可以忽略不配置步骤2)
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)
